comment = { fg = "#6e7781", modifiers = "italic" }
constant = { fg = "#0550ae" }
"constant.character.escape" = { fg = "#0a3069" }
diagnostic = { modifiers = "underlined" }
error = { fg = "#82071e" }
function = { fg = "#8250df" }
"function.macro" = {}
keyword = { fg = "#cf222e" }
"markup.bold" = { fg = "#24292f", modifiers = "bold" }
"markup.heading" = { fg = "#0550ae", modifiers = "bold" }
"markup.italic" = { fg = "#24292f", modifiers = "italic" }
"markup.link" = { fg = "#0a3069", modifiers = "underline" }
"markup.quote" = { fg = "#116329" }
"markup.raw" = { fg = "#0550ae" }
operator = { fg = "#0550ae" }
string = { fg = "#0a3069" }
"string.regexp" = { fg = "#0a3069" }
tag = { fg = "#2ea043" }
type = { fg = "#953800" }
"ui.background" = { bg = "#ffffff", fg = "#24292f" }
"ui.cursor" = { modifiers = "reversed" }
"ui.cursor.match" = { bg = "#bf8700", modifiers = "bold" }
"ui.cursor.primary" = { modifiers = "reversed" }
"ui.cursorline.primary" = { bg = "#f6f8fa" }
"ui.help" = { bg = "#f6f8fa", fg = "#24292f" }
"ui.linenr" = { fg = "#8c959f" }
"ui.linenr.selected" = { fg = "#24292f" }
"ui.menu" = { bg = "#f6f8fa", fg = "#24292f" }
"ui.menu.selected" = { bg = "#f6f8fa" }
"ui.popup" = { bg = "#f6f8fa", fg = "#24292f" }
"ui.selection" = { bg = "#f6f8fa" }
"ui.selection.primary" = { bg = "#f6f8fa" }
"ui.statusline" = { bg = "#f6f8fa", fg = "#24292f" }
"ui.text" = { fg = "#24292f" }
"ui.virtual.ruler" = { bg = "#6e7781" }
"ui.virtual.whitespace" = { fg = "#6e7781" }
"ui.window" = { fg = "#ffffff" }
variable = { fg = "#0550ae" }
"variable.parameter" = { fg = "#953800" }
"variable.other" = { fg = "#24292f" }
warning = { fg = "#7d4e00" }
